### ISSUE TITLE
节点转换为yaml后失效

### ISSUE THREAD

**Issue by Brbrbr1995** [nitezs/sub2clash#47]
`vless://dacd12ee-d990-499a-bc96-9396c9635ff8@188.245.87.153:2096?security=reality&sni=www.python.org&type=http&path=%2Fresource%2F9876%2Fabcd%2Fef12g3h4i5j6k7l8m9n0opqrs%2F2024%2Fxyz%3Fauth%3Dabcd1234efgh5678ijkl9101mnopqrstu%26session%3Dabc1234def5678ghijkl910mno_pqrst%26checksum%3D1a2b3c4d5e6f7g8h9i0jklmnopqrstuvwx&fp=chrome&pbk=TS5-zLzFKNxp7JFXjT_uxmcBKWyW2cesU1YsdgRlQTs&sid=c7ad7539483029e7#🔒_VL-HTTP-RLT_🇩🇪_DE-188.245.87.153:2096
`
```
proxies:
    - type: vless
      name: "\U0001F512_VL-HTTP-RLT_\U0001F1E9\U0001F1EA_DE-188.245.87.153:2096"
      server: 188.245.87.153
      port: 2096
      uuid: dacd12ee-d990-499a-bc96-9396c9635ff8
      tls: true
      network: http
      reality-opts:
        public-key: TS5-zLzFKNxp7JFXjT_uxmcBKWyW2cesU1YsdgRlQTs
        short-id: c7ad7539483029e7
      http-opts:
        headers:
            Host:
                - ""
      servername: www.python.org
      client-fingerprint: chrome
```

**Comment by nitezs** [comment]
正确配置是什么样

**Comment by nitezs** [comment]
```yaml
proxies:
    - type: vless
      name: "\U0001F512_VL-HTTP-RLT_\U0001F1E9\U0001F1EA_DE-188.245.87.153:2096"
      server: 188.245.87.153
      port: 2096
      uuid: dacd12ee-d990-499a-bc96-9396c9635ff8
      tls: true
      network: http
      reality-opts:
        public-key: TS5-zLzFKNxp7JFXjT_uxmcBKWyW2cesU1YsdgRlQTs
        short-id: c7ad7539483029e7
      http-opts:
        path: 
          - /resource/9876/abcd/ef12g3h4i5j6k7l8m9n0opqrs/2024/xyz?auth=abcd1234efgh5678ijkl9101mnopqrstu&session=abc1234def5678ghijkl910mno_pqrst&checksum=1a2b3c4d5e6f7g8h9i0jklmnopqrstuvwx
      servername: www.python.org
      client-fingerprint: chrome
```

试试这个配置能不能用
